In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("student_exam_performance.csv")

In [3]:
print (df)

       student_id  age  gender education_level school_type family_income  \
0      STU_000001   20  Female     High School      Public        Middle
1      STU_000002   17    Male     High School      Public        Middle
2      STU_000003   18   Other   Undergraduate      Public        Middle
3      STU_000004   20    Male     High School      Public        Middle
4      STU_000005   16  Female     High School     Private          High
...           ...  ...     ...             ...         ...           ...
99995  STU_099996   17    Male   Undergraduate      Public  Upper-Middle
99996  STU_099997   14  Female     High School      Public  Upper-Middle
99997  STU_099998   16  Female     High School      Public  Upper-Middle
99998  STU_099999   15  Female     High School     Private          High
99999  STU_100000   18  Female   Undergraduate     Charter  Lower-Middle

      parent_education urban_rural  previous_exam_score  previous_gpa  ...  \
0                  NaN       Rural                78.36          2.95  ...
1                  NaN    Suburban                73.40          2.89  ...
2               Master       Urban                82.76          3.35  ...
3          High School    Suburban                60.61          2.57  ...
4             Bachelor    Suburban                74.79          2.84  ...
...                ...         ...                  ...           ...  ...
99995              NaN    Suburban                78.73           NaN  ...
99996         Bachelor    Suburban                75.70          2.98  ...
99997      High School    Suburban                84.69          3.27  ...
99998           Master       Rural                74.70          3.06  ...
99999              NaN       Urban                76.73          2.97  ...

       exam_difficulty  exam_preparation_days questions_attempted  \
0               Medium                     27                  95
1                 Easy                      4                 100
2                 Easy                     28                  96
3               Medium                     16                  97
4               Medium                     28                  98
...                ...                    ...                 ...
99995           Medium                      5                  95
99996             Easy                     24                  94
99997           Medium                     24                  85
99998           Medium                     28                  93
99999           Medium                      1                  92

       questions_correct  time_management_score  exam_anxiety_level  \
0                     86                    NaN                9.39
1                     86                  87.17                6.31
2                     74                  63.77                9.87
3                     77                  59.51                9.68
4                     52                  84.64               10.00
...                  ...                    ...                 ...
99995                 62                  76.13                8.36
99996                 91                  84.29                8.68
99997                 65                  62.32                9.97
99998                 81                 100.00               10.00
99999                 52                    NaN               10.00

       exam_score performance_grade pass_status performance_level
0           90.40                 A        Pass              High
1           86.21                 A        Pass              High
2           76.11                 B        Pass            Medium
3           79.74                 B        Pass            Medium
4           50.66                 D        Pass               Low
...           ...               ...         ...               ...
99995       66.46                 C        Pass            Medium
99996       96.54                 A        Pass              High
99997       74.66                 C        Pass            Medium
99998       85.85                 A        Pass              High
99999       54.40                 D        Pass               Low

[100000 rows x 44 columns]

In [4]:
df.head(5)

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
0,STU_000001,20,Female,High School,Public,Middle,NaN,Rural,78.36,2.95,...,Medium,27,95,86,NaN,9.39,90.40,A,Pass,High
1,STU_000002,17,Male,High School,Public,Middle,NaN,Suburban,73.40,2.89,...,Easy,4,100,86,87.17,6.31,86.21,A,Pass,High
2,STU_000003,18,Other,Undergraduate,Public,Middle,Master,Urban,82.76,3.35,...,Easy,28,96,74,63.77,9.87,76.11,B,Pass,Medium
3,STU_000004,20,Male,High School,Public,Middle,High School,Suburban,60.61,2.57,...,Medium,16,97,77,59.51,9.68,79.74,B,Pass,Medium
4,STU_000005,16,Female,High School,Private,High,Bachelor,Suburban,74.79,2.84,...,Medium,28,98,52,84.64,10.00,50.66,D,Pass,Low

In [5]:
df.tail(5)

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
99995,STU_099996,17,Male,Undergraduate,Public,Upper-Middle,NaN,Suburban,78.73,NaN,...,Medium,5,95,62,76.13,8.36,66.46,C,Pass,Medium
99996,STU_099997,14,Female,High School,Public,Upper-Middle,Bachelor,Suburban,75.70,2.98,...,Easy,24,94,91,84.29,8.68,96.54,A,Pass,High
99997,STU_099998,16,Female,High School,Public,Upper-Middle,High School,Suburban,84.69,3.27,...,Medium,24,85,65,62.32,9.97,74.66,C,Pass,Medium
99998,STU_099999,15,Female,High School,Private,High,Master,Rural,74.70,3.06,...,Medium,28,93,81,100.00,10.00,85.85,A,Pass,High
99999,STU_100000,18,Female,Undergraduate,Charter,Lower-Middle,NaN,Urban,76.73,2.97,...,Medium,1,92,52,NaN,10.00,54.40,D,Pass,Low

In [6]:
df.describe

<bound method NDFrame.describe of        student_id  age  gender education_level school_type family_income  \
0      STU_000001   20  Female     High School      Public        Middle
1      STU_000002   17    Male     High School      Public        Middle
2      STU_000003   18   Other   Undergraduate      Public        Middle
3      STU_000004   20    Male     High School      Public        Middle
4      STU_000005   16  Female     High School     Private          High
...           ...  ...     ...             ...         ...           ...
99995  STU_099996   17    Male   Undergraduate      Public  Upper-Middle
99996  STU_099997   14  Female     High School      Public  Upper-Middle
99997  STU_099998   16  Female     High School      Public  Upper-Middle
99998  STU_099999   15  Female     High School     Private          High
99999  STU_100000   18  Female   Undergraduate     Charter  Lower-Middle

      parent_education urban_rural  previous_exam_score  previous_gpa  ...  \
0                  NaN       Rural                78.36          2.95  ...
1                  NaN    Suburban                73.40          2.89  ...
2               Master       Urban                82.76          3.35  ...
3          High School    Suburban                60.61          2.57  ...
4             Bachelor    Suburban                74.79          2.84  ...
...                ...         ...                  ...           ...  ...
99995              NaN    Suburban                78.73           NaN  ...
99996         Bachelor    Suburban                75.70          2.98  ...
99997      High School    Suburban                84.69          3.27  ...
99998           Master       Rural                74.70          3.06  ...
99999              NaN       Urban                76.73          2.97  ...

       exam_difficulty  exam_preparation_days questions_attempted  \
0               Medium                     27                  95
1                 Easy                      4                 100
2                 Easy                     28                  96
3               Medium                     16                  97
4               Medium                     28                  98
...                ...                    ...                 ...
99995           Medium                      5                  95
99996             Easy                     24                  94
99997           Medium                     24                  85
99998           Medium                     28                  93
99999           Medium                      1                  92

       questions_correct  time_management_score  exam_anxiety_level  \
0                     86                    NaN                9.39
1                     86                  87.17                6.31
2                     74                  63.77                9.87
3                     77                  59.51                9.68
4                     52                  84.64               10.00
...                  ...                    ...                 ...
99995                 62                  76.13                8.36
99996                 91                  84.29                8.68
99997                 65                  62.32                9.97
99998                 81                 100.00               10.00
99999                 52                    NaN               10.00

       exam_score performance_grade pass_status performance_level
0           90.40                 A        Pass              High
1           86.21                 A        Pass              High
2           76.11                 B        Pass            Medium
3           79.74                 B        Pass            Medium
4           50.66                 D        Pass               Low
...           ...               ...         ...               ...
99995       66.46                 C        Pass            Medium
99996       96.54                 A        Pass              High
99997       74.66                 C        Pass            Medium
99998       85.85                 A        Pass              High
99999       54.40                 D        Pass               Low

[100000 rows x 44 columns]>

In [7]:
df.info

<bound method DataFrame.info of        student_id  age  gender education_level school_type family_income  \
0      STU_000001   20  Female     High School      Public        Middle
1      STU_000002   17    Male     High School      Public        Middle
2      STU_000003   18   Other   Undergraduate      Public        Middle
3      STU_000004   20    Male     High School      Public        Middle
4      STU_000005   16  Female     High School     Private          High
...           ...  ...     ...             ...         ...           ...
99995  STU_099996   17    Male   Undergraduate      Public  Upper-Middle
99996  STU_099997   14  Female     High School      Public  Upper-Middle
99997  STU_099998   16  Female     High School      Public  Upper-Middle
99998  STU_099999   15  Female     High School     Private          High
99999  STU_100000   18  Female   Undergraduate     Charter  Lower-Middle

      parent_education urban_rural  previous_exam_score  previous_gpa  ...  \
0                  NaN       Rural                78.36          2.95  ...
1                  NaN    Suburban                73.40          2.89  ...
2               Master       Urban                82.76          3.35  ...
3          High School    Suburban                60.61          2.57  ...
4             Bachelor    Suburban                74.79          2.84  ...
...                ...         ...                  ...           ...  ...
99995              NaN    Suburban                78.73           NaN  ...
99996         Bachelor    Suburban                75.70          2.98  ...
99997      High School    Suburban                84.69          3.27  ...
99998           Master       Rural                74.70          3.06  ...
99999              NaN       Urban                76.73          2.97  ...

       exam_difficulty  exam_preparation_days questions_attempted  \
0               Medium                     27                  95
1                 Easy                      4                 100
2                 Easy                     28                  96
3               Medium                     16                  97
4               Medium                     28                  98
...                ...                    ...                 ...
99995           Medium                      5                  95
99996             Easy                     24                  94
99997           Medium                     24                  85
99998           Medium                     28                  93
99999           Medium                      1                  92

       questions_correct  time_management_score  exam_anxiety_level  \
0                     86                    NaN                9.39
1                     86                  87.17                6.31
2                     74                  63.77                9.87
3                     77                  59.51                9.68
4                     52                  84.64               10.00
...                  ...                    ...                 ...
99995                 62                  76.13                8.36
99996                 91                  84.29                8.68
99997                 65                  62.32                9.97
99998                 81                 100.00               10.00
99999                 52                    NaN               10.00

       exam_score performance_grade pass_status performance_level
0           90.40                 A        Pass              High
1           86.21                 A        Pass              High
2           76.11                 B        Pass            Medium
3           79.74                 B        Pass            Medium
4           50.66                 D        Pass               Low
...           ...               ...         ...               ...
99995       66.46                 C        Pass            Medium
99996       96.54                 A        Pass              High
99997       74.66                 C        Pass            Medium
99998       85.85                 A        Pass              High
99999       54.40                 D        Pass               Low

[100000 rows x 44 columns]>

In [8]:
df.shape

(100000, 44)

In [9]:
df.index

RangeIndex(start=0, stop=100000, step=1)

In [13]:
df["gender"].unique()

<StringArray>
['Female', 'Male', 'Other']
Length: 3, dtype: str

In [15]:
df["parent_education"]=="Bachelor"

0        False
1        False
2        False
3        False
4         True
         ...
99995    False
99996     True
99997    False
99998    False
99999    False
Name: parent_education, Length: 100000, dtype: bool

In [17]:
df["parent_education"].value_counts()

parent_education
High School    28122
Bachelor       27943
Associate      18640
Master         14043
Doctorate       4726
Name: count, dtype: int64

In [18]:
df["previous_gpa"].median()

np.float64(2.78)

In [19]:
df["age"].median()

np.float64(17.0)